pipelines:
  - name: node_cache_entplus
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: trigger_node
        type: Bash
        configuration:
          inputResources:
            - name: robind_git_resource
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - 16
        execution:
          onExecute:
            - cd $res_robind_git_resource_resourcePath/
            - pwd
            - cd disk-cache-demo/node-project-1
            - pwd
            - ls
            - npm cache verify
            - npm i
            - ls
            - pwd
