resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: trigger_all
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - echo "step_triggered_by_identity_name is $step_triggered_by_identity_name"
            - echo "step_triggered_by_resource_name is $step_triggered_by_resource_name"
            - echo "step_triggered_by_step_name is $step_triggered_by_step_name"
            - |
              if [[ $step_triggered_by_identity_name == "" ]]; then
                echo "It is empty, yes";
              else
                echo "It is not empty, no"
              fi
      - name: trigger_second
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          inputSteps:
            - name: trigger_all
        execution:
          onExecute:
            - echo "it worked"
            - echo "step_triggered_by_identity_name is $step_triggered_by_identity_name"
            - echo "step_triggered_by_resource_name is $step_triggered_by_resource_name"
            - echo "step_triggered_by_step_name is $step_triggered_by_step_name"
      - name: runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - echo "$(dpkg --print-architecture)"
            - aws --version
            - gcloud --version
            - git version
            - jq --version
            - kubectl version --client=true
            - python3 --version
            - node -v
            - go version
            - java -version
            - cpp --version
            - packer version
            - kubectl version --client=true
            - helm version
            - helm2 version
          
