resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - echo "$(dpkg --print-architecture)"
            - aws --version
            - gcloud --version
            - git version
            - jq --version
            - kubectl version --client=true
            - helm version --client=true
            - python3 --version
            - echo "$PATH"
            - sleep 10000
            - npm install -g gulp
            - go version
            - java -version
            - cpp --version
      - name: runtime_image_check_v2
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: jfpip.jfrog.io/jfrog/pipelines-ubuntu22-full
                tag: "0.0.0-f8938_3"
                registry: art_ent
          inputResources:
            - name: resource_1
          integrations: 
            - name: art_ent
        execution:
          onExecute:
            - echo "it worked"
            - echo "$(dpkg --print-architecture)"
            - aws --version
            - gcloud --version
            - git version
            - jq --version
            - kubectl version --client=true
            - helm version --client=true
            - python3 --version
            - echo "$PATH"
            - node -v
            - go version
            - java -version
            - cpp --version
            - packer version
            - kubectl version --client=true
            - helm version
            - helm2 version
      - name: host_check
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - which jfrog
            - whoami
            - pwd
            - /bin/jfrog --version
            - jfrog --version
            - jf --version
            - aws --version
            - gcloud --version
            - git version
            - node18 -v
            - node18 -e 'console.log("version", process.version);'
            - jq --version
            - kubectl version --client=true
            - helm version --client=true
            - helm3 version
            - python3 --version
          onFailure:
            - jf --version
          
