resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: trigger_all
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - ls
            - aws sts get-caller-identity
            - echo "step_triggered_by_identity_name is $step_triggered_by_identity_name"
            - echo "step_triggered_by_resource_name is $step_triggered_by_resource_name"
            - echo "step_triggered_by_step_name is $step_triggered_by_step_name"
            - echo "Step name is $step_name"
            - |
              if [[ $step_triggered_by_identity_name == "" ]]; then
                echo "It is empty, yes";
              else
                echo "It is not empty, no"
              fi
      - name: trigger_second
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          inputSteps:
            - name: trigger_all
        execution:
          onExecute:
            - echo "it worked"
            - echo "step_triggered_by_identity_name is $step_triggered_by_identity_name"
            - echo "step_triggered_by_resource_name is $step_triggered_by_resource_name"
            - echo "step_triggered_by_step_name is $step_triggered_by_step_name"
      - name: base_runtime_image_check_u20arm
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - echo "$(dpkg --print-architecture)"
            - aws --version
            - gcloud --version
            - git version
            - jq --version
            - kubectl version --client=true
            - python3 --version
            - node -v
            - go version
            - java --version
            - cpp --version
            - packer version
            - kubectl version --client=true
            - helm version
            - dotnet --version
            - helm2 version
      - name: base_runtime_image_check_u22
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - echo "$(dpkg --print-architecture)"
            - aws --version
            - gcloud --version
            - git version
            - jq --version
            - kubectl version --client=true
            - python3 --version
            - node -v
            - go version
            - java --version
            - cpp --version
            - packer version
            - kubectl version --client=true
            - helm version
            - dotnet --version
            - helm2 version
      - name: node_runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "18"
        execution:
          onExecute:
            - node -v
      - name: go_runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.21"
        execution:
          onExecute:
            - go version
      - name: cpp_runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - "13"
        execution:
          onExecute:
            - cpp --version
      - name: java_runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "17"
        execution:
          onExecute:
            - java --version
      - name: dotnet_runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              auto:
                language: dotnet
                versions:
                  - "6.0"
        execution:
          onExecute:
            - dotnet --version
      - name: node_runtime_image_check_u20
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-node
                tag: "18"
        execution:
          onExecute:
            - node -v
      - name: go_runtime_image_check_u20
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-go
                tag: "1.21"
        execution:
          onExecute:
            - go version
      - name: cpp_runtime_image_check_u20
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-cpp
                tag: "13"
        execution:
          onExecute:
            - cpp --version
      - name: java_runtime_image_check_u20
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-java
                tag: "17"
        execution:
          onExecute:
            - java --version
      - name: dotnet_runtime_image_check_u20
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-dotnet
                tag: "6.0"
        execution:
          onExecute:
            - dotnet --version
          
