resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    configuration:
      nodePool: kubernetes_testing
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - ls
            - pwd
            - whoami
            - sleep 300
            - ps aux
            - docker ps
          
