resources:
  - name: robind_git_resource
    type: GitRepo
    configuration:
      gitProvider: robind
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: cache_testing_entplus
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: trigger_node
        type: Bash
        configuration:
          inputResources:
            - name: robind_git_resource
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - 10
        execution:
          onExecute:
            - echo "it worked"
            - sleep 100000
      - name: trigger_go
        type: Bash
        configuration:
          inputResources:
            - name: robind_git_resource
          inputSteps:
            - name: trigger_node
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 8
        execution:
          onExecute:
            - echo "it worked"
            - sleep 100000
      # - name: trigger_second
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     inputSteps:
      #       - name: trigger_all
      #   execution:
      #     onExecute:
      #       - echo "it worked"
      #       - echo "step_triggered_by_identity_name is $step_triggered_by_identity_name"
      #       - echo "step_triggered_by_resource_name is $step_triggered_by_resource_name"
      #       - echo "step_triggered_by_step_name is $step_triggered_by_step_name"
      # - name: base_runtime_image_check_u20arm
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #   execution:
      #     onExecute:
      #       - echo "it worked"
      #       - echo "$(dpkg --print-architecture)"
      #       - aws --version
      #       - gcloud --version
      #       - git version
      #       - jq --version
      #       - kubectl version --client=true
      #       - python3 --version
      #       - node -v
      #       - go version
      #       - java --version
      #       - cpp --version
      #       - packer version
      #       - kubectl version --client=true
      #       - helm version
      #       - dotnet --version
      #       - helm2 version
      # - name: base_runtime_image_check_u22
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #   execution:
      #     onExecute:
      #       - echo "it worked"
      #       - echo "$(dpkg --print-architecture)"
      #       - aws --version
      #       - gcloud --version
      #       - git version
      #       - jq --version
      #       - kubectl version --client=true
      #       - python3 --version
      #       - node -v
      #       - go version
      #       - java --version
      #       - cpp --version
      #       - packer version
      #       - kubectl version --client=true
      #       - helm version
      #       - dotnet --version
      #       - helm2 version
      # - name: node_runtime_image_check
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           registry: entplus
      #           name: jfpip.jfrog.io/jfrog/pipelines-centos7-node
      #           tag: "18-2650747"
      #   execution:
      #     onExecute:
      #       - echo $PATH
      #       - node -v
      # - name: go_runtime_image_check
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           registry: entplus
      #           name: jfpip.jfrog.io/jfrog/pipelines-centos7-go
      #           tag: "1.21-2648602"
      #   execution:
      #     onExecute:
      #       - go version
      # - name: cpp_runtime_image_check
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           registry: entplus
      #           name: jfpip.jfrog.io/jfrog/pipelines-centos7-cpp
      #           tag: "13-2649412"
      #   execution:
      #     onExecute:
      #       - cpp --version
      # - name: java_runtime_image_check
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           registry: entplus
      #           name: jfpip.jfrog.io/jfrog/pipelines-centos7-java
      #           tag: "17-2648602"
      #   execution:
      #     onExecute:
      #       - java --version
      # - name: dotnet_runtime_image_check
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           registry: entplus
      #           name: jfpip.jfrog.io/jfrog/pipelines-centos7-dotnet
      #           tag: "6.0-2648602"
      #   execution:
      #     onExecute:
      #       - dotnet --version
      # - name: node_runtime_image_check_u20
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-node
      #           tag: "18"
      #   execution:
      #     onExecute:
      #       - node -v
      # - name: go_runtime_image_check_u20
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-go
      #           tag: "1.21"
      #   execution:
      #     onExecute:
      #       - go version
      # - name: cpp_runtime_image_check_u20
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-cpp
      #           tag: "13"
      #   execution:
      #     onExecute:
      #       - cpp --version
      # - name: java_runtime_image_check_u20
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-java
      #           tag: "17"
      #   execution:
      #     onExecute:
      #       - java --version
      # - name: dotnet_runtime_image_check_u20
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: robind_git_resource
      #     runtime:
      #       type: image
      #       image:
      #         custom:
      #           name: releases-docker.jfrog.io/jfrog/pipelines-ubuntu20arm-dotnet
      #           tag: "6.0"
      #   execution:
      #     onExecute:
      #       - dotnet --version
          
