resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    steps:
      - name: step_1
        type: PowerShell
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - dir
            
          
