resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    steps:
      - name: step_1
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-u20node
                tag: "16"
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
      - name: step_2
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/artifactory/docker/jfrog/pipelines-u20armnode
                tag: "latest"
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
      - name: step_3
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: jfpip.jfrog.io/jfrog/pipelines-ubuntu22-full
                tag: "0.0.0-f893"
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
          
