resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: runtime_image_check
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "it worked"
            - echo "$(dpkg --print-architecture)"
            - aws --version
            - gcloud --version
            - git version
            - jq --version
            - kubectl version --client=true
            - python3 --version
            - node -v
            - go version
            - java -version
            - cpp --version
            - packer version
            - kubectl version --client=true
            - helm version
            - helm2 version
          
