resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main

pipelines:
  - name: checking_rabbitmq
    steps:
      - name: hello_world
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo "hello world"
            - sleep 60
            - echo "Slept and woke up"


