resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - ls
            - pwd
            - whoami
            - ps aux
            - cat /var/opt/jfrog/pipelines/data/hello_world/runs/5/steps/step_1/5/stepletScript.sh
            - killall5 -9
          
