resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main
pipelines:
  - name: hello_world
    configuration:
      nodePool: testing_node_pools
      runtime:
        type: image
        image:
          custom:
            registry: docker_hub
            sourceRepository: busybox
            name: busybox
            tag: latest
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - ls
            - pwd
            - whoami
            - ps aux
            - docker ps
          
