resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: github_test
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: main

pipelines:
  - name: clean_old_namespaces
    steps:
      - name: run_python_cleanup_script
        type: Bash
        configuration:
          environmentVariables:
            age_to_delete:
              default: 10
              description: Deletes namespaces older than age_to_delete
              allowCustom: true
            name_regex:
              default: "default"
              description: Deletes namespaces older matching the regex provided
              allowCustom: true
          integrations:
            - name: test_kubernetes
        execution:
          onExecute:
            - ls ${res_resource_1_resourcePath}
            - find . -type f -name "*.txt"
            - "pip3 install -r ${res_resource_1_resourcePath}/namespace-cleanup/requirements.txt"
            - "python3 ${res_resource_1_resourcePath}/namespace-cleanup/cleanup_ns.py $age_to_delete $name_regex"


